(()=>{
'use strict';
const D=window.V6_DATA;
const STORAGE='vtm_v6_alpha_chargen_v0_5_0';
const LEGACY_STORAGE=['vtm_v6_alpha_chargen_v0_4_2','vtm_v6_alpha_chargen_v0_4_1','vtm_v6_alpha_chargen_v0_4_0','vtm_v6_alpha_chargen_v0_3_0','vtm_v6_alpha_chargen_v0_2_1','vtm_v6_alpha_chargen_v0_2_0','vtm_v6_alpha_chargen_v0_1_0'];
const STEPS=[
  ['Creature','What are you?'],['Clan','Your Clan'],['Sire','Sire & Generation'],['Lifepaths','Your Lifepaths'],
  ['Attributes','Attributes'],['Skills','Skills'],['Focuses','Focuses'],['Powers','Disciplines, Traits & Merits'],
  ['Humanity','Humanity & Nature'],['Resources','Your Resources'],['Finish','Finishing Touches']
];
const byId=(arr,id)=>arr.find(x=>x.id===id);
const e=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dots=n=>'●'.repeat(Math.max(0,Number(n)||0));
const sum=o=>Object.values(o||{}).reduce((a,b)=>a+(Number(b)||0),0);
const tierOf=()=>state.creature.includes('elder')?'elder':state.creature.includes('ancilla')?'ancilla':'neonate';
const tierRank=t=>D.tierRank[t]||0;
const creature=()=>byId(D.creatures,state.creature)||byId(D.creatures,'vampire_neonate');
const attrById=id=>byId(D.attributes,id), skillById=id=>byId(D.skills,id), discById=id=>byId(D.disciplines,id), clanById=id=>byId(D.clans,id), lpById=id=>byId(D.lifepaths,id);
const sourceGapDisc=id=>discById(id)?.powers?.length===0;

function blankState(){
 const attrs={};D.attributes.forEach(a=>attrs[a.id]=1);
 return {schemaVersion:1,step:0,creature:'vampire_neonate',young:false,
   clan:{id:null,choice:null,caitiffDisciplines:[]},
   sire:{type:null,relatedClan:null,bonusDiscipline:null},generation:13,
   lifepaths:[],attributes:{roles:{physical:'primary',social:'secondary',mental:'tertiary'},ratings:attrs},
   freeSkills:{},focuses:{},disciplines:{clanDots:{},powers:[]},traits:[],merits:[],
   humanity:{position:0,nature:null},resources:{free:[]},
   identity:{name:'',alias:'',apparentAge:'',actualAge:'',nostalgicDecade:'',flaws:'',items:[]},
   info:null};
}
let state=load()||blankState();
normalizeState();
function load(){try{const current=JSON.parse(localStorage.getItem(STORAGE)||'null');if(current)return current;for(const key of LEGACY_STORAGE){const legacy=JSON.parse(localStorage.getItem(key)||'null');if(!legacy)continue;if(key.endsWith('_v0_1_0')){const oldStep=Number(legacy.step||0),map=[0,1,2,3,4,7,8,9,10];legacy.step=map[oldStep]??0;}legacy.focuses={};return legacy}return null}catch{return null}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function normalizeState(){
 if(!state||state.schemaVersion!==1)state=blankState();
 if(!state.attributes?.ratings)state.attributes=blankState().attributes;
 D.attributes.forEach(a=>{if(!Number.isFinite(Number(state.attributes.ratings[a.id])))state.attributes.ratings[a.id]=1});
 ensureLpSlots();enforceSkillCaps();ensureItems();
}
function tierGenerations(){return D.generationByTier[tierOf()]||[13,12,11]}
function ensureGeneration(){const arr=tierGenerations();if(!arr.includes(Number(state.generation)))state.generation=arr[0]}
function lpCount(){return state.young&&tierOf()==='neonate'?1:creature().lifepaths}
function lpSkillBudget(){return state.young&&tierOf()==='neonate'?8:5}
function lpResourceBudget(){return state.young&&tierOf()==='neonate'?5:3}
function ensureLpSlots(){
 const n=lpCount();state.lifepaths=Array.isArray(state.lifepaths)?state.lifepaths:[];
 while(state.lifepaths.length<n)state.lifepaths.push({id:null,skillDots:{},resourceDots:{},custom:null});
 if(state.lifepaths.length>n)state.lifepaths.length=n;
}
function ensureItems(){const n=lpCount();state.identity.items=Array.isArray(state.identity.items)?state.identity.items:[];while(state.identity.items.length<n)state.identity.items.push('');if(state.identity.items.length>n)state.identity.items.length=n}
function allowedLifepaths(){const tr=tierRank(tierOf());return D.lifepaths.filter(lp=>lp.type==='mortal'||tierRank(lp.tier)<=tr)}
function lpDef(slot){const x=state.lifepaths[slot];if(!x)return null;if(x.id==='__custom__')return customLpDef(x);return lpById(x.id)}
function customLpDef(x){
 const c=x.custom||{};return {id:'__custom__',name:c.name||'Custom Lifepath',description:c.description||'',type:'custom',tier:'custom',skills:(c.skills||[]).map(id=>({skill:id,focus:''})),resources:(c.resources||[]).map(r=>({type:r.type,label:r.label||''}))};
}
function lifepathSkillRating(id){return state.lifepaths.reduce((n,lp)=>n+Number(lp.skillDots?.[id]||0),0)}
function lifepathSkillSources(id){const out=[];state.lifepaths.forEach((lp,i)=>{const n=Number(lp.skillDots?.[id]||0),d=lpDef(i);if(n&&d)out.push({source:d.name,dots:n})});return out}
function lifepathCapSources(id){const out=[];state.lifepaths.forEach((lp,i)=>{const d=lpDef(i);if(d&&(d.skills||[]).some(x=>x.skill===id))out.push(d.name)});return out}
function skillCap(id){return 3+lifepathCapSources(id).length}
function finalSkill(id){return lifepathSkillRating(id)+Number(state.freeSkills[id]||0)}
function enforceSkillCaps(){D.skills.forEach(s=>{let excess=finalSkill(s.id)-skillCap(s.id);if(excess<=0)return;const free=Number(state.freeSkills[s.id]||0),cut=Math.min(excess,free);if(cut){state.freeSkills[s.id]=free-cut;if(state.freeSkills[s.id]<=0)delete state.freeSkills[s.id];excess-=cut}if(excess<=0)return;for(let i=state.lifepaths.length-1;i>=0&&excess>0;i--){const lp=state.lifepaths[i],cur=Number(lp.skillDots?.[s.id]||0),c=Math.min(excess,cur);if(c){lp.skillDots[s.id]=cur-c;if(lp.skillDots[s.id]<=0)delete lp.skillDots[s.id];excess-=c}}});ensureFocusSlots()}
function finalSkills(){const o={};D.skills.forEach(s=>o[s.id]=finalSkill(s.id));return o}
function focusThresholds(id){const n=finalSkill(id);return [1,3,5].filter(t=>n>=t)}
function requiredFocuses(id){return focusThresholds(id).length}
function lpSkillEntry(def,id){return (def?.skills||[]).find(x=>x.skill===id)||null}
function focusSlotDefs(id){return focusThresholds(id).map(threshold=>({threshold}))}
function ensureFocusSlots(){state.focuses=state.focuses||{};D.skills.forEach(s=>{const slots=focusSlotDefs(s.id),old=Array.isArray(state.focuses[s.id])?state.focuses[s.id]:[],a=[];slots.forEach((slot,i)=>a[i]=String(old[i]||'').trim());state.focuses[s.id]=a;});}
function lifepathFocusRecommendations(id){
 const out=[];
 state.lifepaths.forEach((lp,i)=>{const d=lpDef(i),x=lpSkillEntry(d,id);if(!d||!x)return;const values=[];(x.focusOptions||[]).forEach(v=>{if(v&&!values.includes(v))values.push(v)});if(x.focus&&!/^choose /i.test(String(x.focus).trim())&&!values.includes(x.focus))values.push(x.focus);const prompt=x.focusPrompt||(/^choose /i.test(String(x.focus||''))?String(x.focus):'');if(values.length||prompt)out.push({source:d.name,values,prompt});});
 return out;
}
function rawFocusSuggestions(id){return (skillById(id)?.focuses||[]).map(f=>f.name).filter(Boolean)}
function lifepathFocusLabel(x){if(!x)return'';if(Array.isArray(x.focusOptions)&&x.focusOptions.length)return x.focusOptions.join(' / ');if(x.focusPrompt)return x.focusPrompt;return x.focus||''}
function clanDisciplineIds(){
 const c=clanById(state.clan.id);if(!c)return[];const r=c.disciplineRule||{};
 if(r.random)return state.clan.caitiffDisciplines||[];
 return [...(r.fixed||[]),...(r.choice?[state.clan.choice].filter(Boolean):[])];
}
function allClanPossibleDiscs(clanId){const c=clanById(clanId);if(!c)return[];const r=c.disciplineRule||{};if(r.random)return D.disciplines.map(d=>d.id);return [...(r.fixed||[]),...(r.choice||[])];}
function sireAllowedDisciplines(){
 const s=byId(D.sires,state.sire.type);if(!s)return[];
 if(['adoptive_sire','brood_child'].includes(s.id))return allClanPossibleDiscs(state.sire.relatedClan);
 const map={caring_sire:['fortitude','potence','presence'],cruel_sire:['dominate','fortitude','obfuscate'],manipulative_sire:['dominate','potence','presence'],secretive_sire:['auspex','celerity','obfuscate'],unknown_sire:['celerity','fortitude','potence'],vigilant_sire:['auspex','dominate','fortitude']};
 return map[s.id]||[];
}
function disciplineRating(id){return Number(state.disciplines.clanDots[id]||0)+(state.sire.bonusDiscipline===id?1:0)}
function totalClanDisciplineDots(){return sum(state.disciplines.clanDots)}
function eligiblePowers(){
 const out=[];D.disciplines.forEach(d=>{const r=disciplineRating(d.id);if(r<1)return;(d.powers||[]).forEach(p=>{if(p.rank<=r)out.push({...p,disciplineId:d.id,disciplineName:d.name})})});return out;
}
function selectedPowerKey(p){return `${p.disciplineId}:${p.id}`}
function powerSelected(did,pid){return state.disciplines.powers.some(x=>x.disciplineId===did&&x.powerId===pid)}
function generationModifier(){return Number(D.generationModifiers[String(state.generation)]||creature().generationModifier||1)}
function vitaeMax(){return 10+Number(state.attributes.ratings.stamina||0)}
function willpowerMax(){return 5+Number(state.attributes.ratings.composure||0)+Number(state.attributes.ratings.resolve||0)}
function roleBudget(cat){const c=creature();const role=state.attributes.roles[cat.toLowerCase()];return role==='primary'?c.attributeBudgets[0]:role==='secondary'?c.attributeBudgets[1]:c.attributeBudgets[2]}
function categorySum(cat){return D.attributes.filter(a=>a.category===cat).reduce((n,a)=>n+Number(state.attributes.ratings[a.id]||0),0)}
function categorySpent(cat){return categorySum(cat)-D.attributes.filter(a=>a.category===cat).length}
function totalAttributeSpent(){return D.attributes.reduce((n,a)=>n+Math.max(0,Number(state.attributes.ratings[a.id]||1)-1),0)}
function attrMax(){return creature().maxDots||5}
function tierDisciplineCaps(){return {neonate:{clan:5,nonClan:3},ancilla:{clan:7,nonClan:5},elder:{clan:8,nonClan:7}}[tierOf()]||{clan:5,nonClan:3}}
function freeResourceSpent(){return state.resources.free.reduce((n,r)=>n+Number(r.dots||0),0)}
function lpResourceSpent(slot){return sum(state.lifepaths[slot]?.resourceDots||{})}
function sourceResourceEntries(){const out=[];state.lifepaths.forEach((lp,i)=>{const d=lpDef(i);(d?.resources||[]).forEach((r,ri)=>{const n=Number(lp.resourceDots?.[String(ri)]||0);if(n)out.push({source:d.name,type:r.type,label:r.label||'',dots:n})})});return out}
function normalizeResourceLabel(label){return String(label||'').trim().replace(/\s+/g,' ').toLowerCase()}
function aggregatedLifepathResources(){const map=new Map();for(const r of sourceResourceEntries()){const key=`${r.type}|${normalizeResourceLabel(r.label)}`;if(!map.has(key))map.set(key,{type:r.type,label:r.label||'',dots:0,sources:[]});const x=map.get(key);x.dots+=Number(r.dots||0);x.sources.push({source:r.source,dots:Number(r.dots||0)})}return [...map.values()]}
function resourceType(id){return byId(D.resourceTypes,id)}

function prereqEligible(text){
 text=String(text||'').replace(/\s+/g,' ').trim();const tr=tierRank(tierOf());
 if(/Ancilla or stronger/i.test(text)&&tr<2)return false;if(/Neonate or stronger/i.test(text)&&tr<1)return false;
 const attrMatch=text.match(/At least\s+(\d+)\s+dots?\s+in\s+Stamina/i);if(attrMatch&&Number(state.attributes.ratings.stamina)<Number(attrMatch[1]))return false;
 const either=[...text.matchAll(/(?:at least\s+)?(\d+)\s+dots?\s+in\s+either\s+([A-Za-z ]+?)\s+or\s+([A-Za-z ]+?)(?:\.|$)/gi)];
 for(const m of either){const n=Number(m[1]),a=discIdByName(m[2]),b=discIdByName(m[3]);if(Math.max(disciplineRating(a),disciplineRating(b))<n)return false;}
 let stripped=text.replace(/(?:at least\s+)?\d+\s+dots?\s+in\s+either\s+[A-Za-z ]+?\s+or\s+[A-Za-z ]+?(?:\.|$)/gi,'');
 const reqs=[...stripped.matchAll(/(?:At least\s+)?(\d+)\s+dots?\s+in\s+([A-Za-z ]+?)(?=\s+and|\.|$)/gi)];
 for(const m of reqs){const id=discIdByName(m[2]);if(id&&disciplineRating(id)<Number(m[1]))return false;}
 return true;
}
function discIdByName(name){const n=String(name||'').trim().toLowerCase();return D.disciplines.find(d=>d.name.toLowerCase()===n)?.id||null}
function traitEligible(t){return tierRank(tierOf())>=tierRank(t.tier)&&prereqEligible(t.prerequisites)}

function setInfo(obj,openMobile=false){state.info=obj;renderInfo();if(openMobile&&innerWidth<=900)openDrawer()}
function infoForStep(i){
 const defs=[
  {kicker:'Step 1 · Player Packet',title:'What Are You?',summary:'Choose the vampire tier. The tier sets maximum dots and the character-creation budgets for Lifepaths, Attributes, Disciplines, powers, Merits, Clan Traits, Skills, and Resources.',body:'This build focuses on Vampire Neonate, Ancilla, and Elder. Ghoul and Duskborn remain outside the enabled flow for now.'},
  {kicker:'Step 2 · Player Packet',title:'Your Clan',summary:'Clan determines your curse, Beast/frenzy expression, clan Disciplines, and available Clan Traits.',body:'Select a clan, then resolve any required variable Discipline immediately. For Lasombra this means choosing Corruption or Oblivion before Discipline-dot allocation.'},
  {kicker:'Step 3 · Player Packet',title:'Sire & Generation',summary:'Your sire type grants 1 additional Discipline dot. Generation places you in a power category and sets the generation modifier.',body:'The Storyteller typically chooses generation. Neonates are 13th–11th generation, Ancillae 10th–9th, and Elders 8th–6th in the supplied Alpha rules.'},
  {kicker:'Step 4 · Player Packet',title:'Lifepaths',summary:'Lifepaths represent past professions, identities, and roles. Each Lifepath gives Skill and Resource dots.',body:`Each Lifepath normally grants 5 Skill dots among its listed Skills and 3 Resource dots among its listed Resources. ${D.lifepathCompetence}`},
  {kicker:'Step 5 · Player Packet',title:'Attributes',summary:'Attributes define the character’s potential in Physical, Social, and Mental categories.',body:'Assign primary, secondary, and tertiary category budgets. Each Attribute begins at 1. Use the Info button to read what each rating means; changing dots on mobile no longer opens the help drawer automatically.'},
  {kicker:'Step 5 · Player Packet + house rule',title:'Skills',summary:'Skills define learned competency. Lifepaths contribute dots first, then you distribute the free Skill dots from the tier budget.',body:'House rule: the base chargen Skill cap is 3, and each selected Lifepath that lists a Skill raises that Skill’s cap by +1, whether or not a Lifepath dot was assigned to it. Focus selection is handled on the next page.'},
  {kicker:'Step 5 · Player Packet',title:'Focuses',summary:'A Skill has one Focus at rating 1, a second at 3, and a third at 5. Rating 2 therefore still has exactly one Focus.',body:'All Focus slots are player choices. Parenthetical Focuses printed in selected Lifepaths are shown as recommendations during selection, alongside the Skill’s RAW example Focuses. They never lock or auto-fill a Focus, and you may type another relevant Focus.'},
  {kicker:'Step 6 · Player Packet',title:'Disciplines, Clan Traits & Merits',summary:'Discipline dots unlock powers by rank. Clan Traits and Merits provide distinctive passive or activated abilities.',body:'Choose the exact number of powers, Clan Traits, and Merits from the Dot Distribution table. A power’s rank cannot exceed your dots in its Discipline. Prerequisites are enforced when the Alpha text provides them.'},
  {kicker:'Step 7 · Player Packet',title:'Humanity Scale & Nature',summary:'A vampire begins balanced in the center of the seven-position Humanity Scale. Nature defines the mortal axis and its outburst.',body:'Ancillae may begin at stage 1 toward either side if the Storyteller chooses an unbalanced beginning. Elders may begin at stage 2 toward either side.'},
  {kicker:'Step 8 · Player Packet',title:'Resources',summary:'Resources are Physical Assets, Social Assets, and Wealth. Lifepaths grant Resource dots; the Dot Distribution table grants additional free Resource dots.',body:D.resourceRuleText},
  {kicker:'Step 9 · Player Packet',title:'Finishing Touches',summary:'Calculate Vitae and Willpower, then define identity details, important items, and optional Flaws.',body:'Vitae Maximum = 10 + Stamina. Willpower Maximum = 5 + Composure + Resolve. You receive one additional important item per Lifepath, provided it fits that Lifepath. Flaws have no fixed mechanical bonus or penalty in the Alpha packet.'}
 ];return defs[i];
}
function infoAttribute(id){const a=attrById(id);return {kicker:`${a.category} Attribute`,title:a.name,summary:a.description,meta:[['Current rating',String(state.attributes.ratings[id])],['Tier Max Dots',String(attrMax())],['Highest legal now',String(maxLegalAttrRating(a))],['Category allocation',`${categorySpent(a.category)} / ${roleBudget(a.category)} distributed`],['Final category total',String(categorySum(a.category))]],ratings:a.ratings,maxRating:attrMax(),currentRating:Number(state.attributes.ratings[id]),body:(a.mechanics||[]).join('\n\n'),source:'Player Packet · Step 1 + Step 5: Maximum Dots and Attributes'};}
function infoSkill(id){const s=skillById(id),caps=lifepathCapSources(id);return {kicker:'Skill',title:s.name,summary:s.description,meta:[['Current rating',String(finalSkill(id))],['Chargen cap',String(skillCap(id))],['Lifepath cap bonus',caps.length?`+${caps.length} · ${caps.join(' · ')}`:'—'],['Focus slots',String(requiredFocuses(id))]],body:`The Alpha packet provides a Skill description and example Focuses, but no rating-by-rating Skill scale comparable to Attributes.\n\n${(s.focuses||[]).map(f=>`${f.name}: ${f.description}`).join('\n\n')}`,source:'Player Packet · Step 5: Skills & Focuses · cap modified by project house rule'};}
function infoClan(id){const c=clanById(id);return {kicker:c.complete?'Clan · Alpha entry complete':'Clan · Alpha entry incomplete',title:c.name,summary:c.description,meta:[['Disciplines',c.disciplineText],['Curse',c.curseName],['Frenzy',c.frenzyName]],body:[c.overview,c.beastText,c.curseText,c.frenzyText].filter(Boolean).join('\n\n'),source:'Player Packet · Chapter 3: The Clans'};}
function infoLp(slot){const d=lpDef(slot);if(!d)return infoForStep(3);return {kicker:'Lifepath',title:d.name,summary:d.description,meta:[['Skill dots',`${sum(state.lifepaths[slot].skillDots)} / ${lpSkillBudget()}`],['Resource dots',`${lpResourceSpent(slot)} / ${lpResourceBudget()}`]],body:`Skills: ${(d.skills||[]).map(x=>skillById(x.skill)?.name+(lifepathFocusLabel(x)?` (suggested Focus: ${lifepathFocusLabel(x)})`:'')).join(', ')}\n\nResources: ${(d.resources||[]).map(x=>(resourceType(x.type)?.name||x.type)+(x.label?`: ${x.label}`:'')).join(', ')}\n\n${D.lifepathCompetence}`,source:'Player Packet · Step 4: Lifepaths'};}
function infoPower(did,pid){const d=discById(did),p=d?.powers.find(x=>x.id===pid);if(!p)return infoForStep(7);return {kicker:`${d.name} · ${p.rank}-dot ${p.category}`,title:p.name,summary:d.description,meta:[['Activate',p.activate||'—'],['Attribute',p.attribute||'—'],['Cost',p.cost||'—'],['Difficulty',p.difficulty||'—'],['Distance',p.distance||'—'],['Duration',p.duration||'—']],body:p.text,source:`Player Packet · Chapter 5: ${d.name}`};}
function infoTrait(t){return {kicker:`Clan Trait · ${t.tier}`,title:t.name,summary:`Prerequisites: ${t.prerequisites}`,body:t.text,source:'Player Packet · Chapter 3: The Clans'};}
function infoMerit(m){return {kicker:'Merit',title:m.name,summary:m.summary,meta:[['Prerequisites',m.prerequisites||'—']],body:m.text,source:'Player Packet · Step 6: Merits'};}
function infoNature(n){return {kicker:'Nature',title:n.name,summary:n.summary,body:n.text,source:'Player Packet · Step 7: Humanity Scale and Your Nature'};}
function infoResource(id){const r=resourceType(id);return {kicker:r.category,title:r.name,summary:r.description,body:'Each Physical or Social Asset should be specific to the character. The number of dots represents the scale, quality, reach, or NPC Level described by that Resource type.',source:'Player Packet · Step 8: Your Resources'};}
function renderInfo(){const I=state.info||infoForStep(state.step);const meta=(I.meta||[]).map(([k,v])=>`<div class="kv"><span>${e(k)}</span><b>${e(v)}</b></div>`).join('');let ratings='';if(I.ratings){const max=Number(I.maxRating||Math.max(...Object.keys(I.ratings).map(Number)));ratings='<div class="ratingList">'+Array.from({length:max},(_,i)=>{const n=i+1,t=I.ratings[String(n)],missing=!t;return `<div class="ratingItem ${n===I.currentRating?'active':''}"><div class="ratingDots">Rating ${n} · ${dots(n)}</div><div class="meta">${e(t||'The supplied Alpha packet gives no qualitative description for this Attribute rating.')}</div>${missing?'<div class="tagrow"><span class="tag warn">Alpha source gap</span></div>':''}</div>`}).join('')+'</div>'}
 const body=String(I.body||'').split(/\n\n+/).filter(Boolean).map(p=>`<p>${e(p)}</p>`).join('');
 document.getElementById('infoContent').innerHTML=`<div class="infoKicker">${e(I.kicker||'Rules reference')}</div><h2>${e(I.title||'Information')}</h2><div class="infoSummary">${e(I.summary||'')}</div>${meta?`<div class="infoMeta">${meta}</div>`:''}${ratings}<div class="infoBody">${body}</div><div class="infoSource">${e(I.source||'VTM V6 Alpha Player Packet')}</div>`;
}
function openDrawer(){document.getElementById('infoPanel').classList.add('open');document.getElementById('drawerBack').classList.add('open')}
function closeDrawer(){document.getElementById('infoPanel').classList.remove('open');document.getElementById('drawerBack').classList.remove('open')}

function issue(severity,msg){return {severity,msg}}
function validateStep(i){const out=[];const c=creature();
 if(i===0){if(!['vampire_neonate','vampire_ancilla','vampire_elder'].includes(state.creature))out.push(issue('error','Choose a supported Vampire tier.'))}
 if(i===1){const cl=clanById(state.clan.id);if(!cl)out.push(issue('incomplete','Choose a Clan.'));else{const r=cl.disciplineRule||{};if(r.choice&&!state.clan.choice)out.push(issue('incomplete',`Choose ${cl.name}’s variable third Discipline.`));if(r.random&&(state.clan.caitiffDisciplines||[]).length!==3)out.push(issue('incomplete','Caitiff requires 3 randomly determined Disciplines.'));if(!cl.complete)out.push(issue('warning','This clan remains partially in development in the supplied Alpha packet.'))}}
 if(i===2){if(!state.sire.type)out.push(issue('incomplete','Choose a sire type.'));if(['adoptive_sire','brood_child'].includes(state.sire.type)&&!state.sire.relatedClan)out.push(issue('incomplete','Choose the adoptive sire / broodmate Clan.'));if(!state.sire.bonusDiscipline)out.push(issue('incomplete','Choose the bonus Discipline granted by the sire type.'));if(!tierGenerations().includes(Number(state.generation)))out.push(issue('error','Generation is outside the selected tier.'))}
 if(i===3){ensureLpSlots();state.lifepaths.forEach((lp,slot)=>{const d=lpDef(slot);if(!d)out.push(issue('incomplete',`Choose Lifepath ${slot+1}.`));else{if(lp.id==='__custom__'){if(!lp.custom?.name?.trim())out.push(issue('incomplete',`Custom Lifepath ${slot+1} needs a name.`));if((lp.custom?.skills||[]).length!==5)out.push(issue('incomplete',`Custom Lifepath ${slot+1} must define exactly 5 Skills.`));if((lp.custom?.resources||[]).length!==3)out.push(issue('incomplete',`Custom Lifepath ${slot+1} must define exactly 3 Resources.`));if((lp.custom?.resources||[]).some(r=>!resourceType(r.type)))out.push(issue('incomplete',`Custom Lifepath ${slot+1}: choose all 3 Resource types.`));}if(sum(lp.skillDots)!==lpSkillBudget())out.push(issue('incomplete',`${d.name}: spend exactly ${lpSkillBudget()} Lifepath Skill dots.`));if(lpResourceSpent(slot)!==lpResourceBudget())out.push(issue('incomplete',`${d.name}: spend exactly ${lpResourceBudget()} Lifepath Resource dots.`));}})}
 if(i===4){['Physical','Social','Mental'].forEach(cat=>{if(categorySpent(cat)!==roleBudget(cat))out.push(issue('incomplete',`${cat}: distribute exactly ${roleBudget(cat)} Attribute dots above the three baseline dots (${categorySpent(cat)} distributed).`))});const roles=Object.values(state.attributes.roles);if(new Set(roles).size!==3)out.push(issue('error','Physical, Social, and Mental must use different primary/secondary/tertiary budgets.'));D.attributes.forEach(a=>{const n=Number(state.attributes.ratings[a.id]);if(n<1||n>attrMax())out.push(issue('error',`${a.name} must be between 1 and ${attrMax()}.`));})}
 if(i===5){if(sum(state.freeSkills)!==c.freeSkillDots)out.push(issue('incomplete',`Spend exactly ${c.freeSkillDots} free Skill dots.`));D.skills.forEach(s=>{const n=finalSkill(s.id),cap=skillCap(s.id);if(n>cap)out.push(issue('error',`${s.name} exceeds its house-rule character-creation cap of ${cap}.`))})}
 if(i===6){D.skills.forEach(s=>{const n=finalSkill(s.id),cap=skillCap(s.id),req=requiredFocuses(s.id),arr=state.focuses[s.id]||[];if(n>cap)out.push(issue('error',`${s.name} exceeds its house-rule character-creation cap of ${cap}.`));if(arr.length!==req||arr.some(x=>!String(x).trim()))out.push(issue('incomplete',`${s.name}: fill ${req} Focus slot${req===1?'':'s'} for rating ${n}.`))})}
 if(i===7){const cds=clanDisciplineIds();if(cds.length!==3)out.push(issue('incomplete','Resolve the Clan’s three Disciplines first.'));if(totalClanDisciplineDots()!==c.disciplineDots)out.push(issue('incomplete',`Distribute exactly ${c.disciplineDots} Clan Discipline dots.`));D.disciplines.forEach(d=>{if(disciplineRating(d.id)>c.maxDisciplineDots)out.push(issue('error',`${d.name} exceeds maximum ${c.maxDisciplineDots} dots for this tier.`))});if(state.disciplines.powers.length!==c.disciplinePowers)out.push(issue('incomplete',`Choose exactly ${c.disciplinePowers} Discipline powers.`));state.disciplines.powers.forEach(x=>{const p=discById(x.disciplineId)?.powers.find(p=>p.id===x.powerId);if(!p||p.rank>disciplineRating(x.disciplineId))out.push(issue('error','A selected Discipline power no longer meets its rank requirement.'));else if(p.detailsMissing)out.push(issue('warning',`${p.name} is listed in the Alpha power summary but its full rules entry is missing from the supplied packet.`))});if(state.traits.length!==c.clanTraits)out.push(issue('incomplete',`Choose exactly ${c.clanTraits} Clan Traits.`));if(state.merits.length!==c.merits)out.push(issue('incomplete',`Choose exactly ${c.merits} Merits.`));const cl=clanById(state.clan.id);if(cl&&!cl.complete)out.push(issue('warning','Full Clan Traits are unavailable for this clan in the supplied Alpha packet.'));const usedIncomplete=D.disciplines.filter(d=>disciplineRating(d.id)>0&&sourceGapDisc(d.id));if(usedIncomplete.length)out.push(issue('warning',`No power definitions are supplied for: ${usedIncomplete.map(d=>d.name).join(', ')}.`))}
 if(i===8){if(!state.humanity.nature)out.push(issue('incomplete','Choose a Nature.'));const allowedHumanity=humanityPositions();if(!allowedHumanity.some(x=>x.v===state.humanity.position))out.push(issue('error','Starting Humanity position is not allowed for this tier.'))}
 if(i===9){if(freeResourceSpent()!==c.freeResourceDots)out.push(issue('incomplete',`Spend exactly ${c.freeResourceDots} free Resource dots.`));aggregatedLifepathResources().forEach(r=>{if(Number(r.dots)>attrMax())out.push(issue('error',`${resourceType(r.type)?.name||r.type}${r.label?`: ${r.label}`:''} exceeds the ${attrMax()}-dot character-creation maximum after Lifepath sources are combined.`))});state.resources.free.forEach((r,idx)=>{if(!resourceType(r.type))out.push(issue('error',`Free Resource ${idx+1} has an unknown type.`));if(Number(r.dots)<1||Number(r.dots)>attrMax())out.push(issue('error',`Free Resource ${idx+1} has an invalid rating.`));if(r.type!=='wealth'&&!String(r.label||'').trim())out.push(issue('incomplete',`${resourceType(r.type)?.name||'Resource'} needs a specific label.`))})}
 if(i===10){ensureItems();if(!state.identity.name.trim())out.push(issue('incomplete','Enter a character name.'));state.identity.items.forEach((x,j)=>{if(!String(x).trim())out.push(issue('incomplete',`Important item ${j+1} is empty.`))})}
 return out;
}
function allIssues(){return STEPS.flatMap((_,i)=>validateStep(i).map(x=>({...x,step:i})))}
function isStepDone(i){return !validateStep(i).some(x=>['error','incomplete'].includes(x.severity))}

function render(){ensureGeneration();ensureLpSlots();ensureFocusSlots();ensureItems();renderNav();renderMain();renderInfo();save();}
function stepProgress(i){const c=creature();
 if(i===0)return state.creature?'1/1 selected':'0/1 selected';
 if(i===1){const cl=clanById(state.clan.id),base=cl?1:0,extra=cl?.disciplineRule?.choice?`${state.clan.choice?1:0}/1 Discipline`:cl?.disciplineRule?.random?`${(state.clan.caitiffDisciplines||[]).length}/3 Disciplines`:'';return `${base}/1 Clan${extra?` · ${extra}`:''}`}
 if(i===2){const related=['adoptive_sire','brood_child'].includes(state.sire.type),done=(state.sire.type?1:0)+(state.generation?1:0)+(state.sire.bonusDiscipline?1:0)+(related&&state.sire.relatedClan?1:0),total=3+(related?1:0);return `${done}/${total} choices · ${Math.max(0,total-done)} left`}
 if(i===3){const chosen=state.lifepaths.filter((_,j)=>!!lpDef(j)).length,skillLeft=state.lifepaths.reduce((n,lp)=>n+Math.max(0,lpSkillBudget()-sum(lp.skillDots)),0),resLeft=state.lifepaths.reduce((n,lp,j)=>n+(lpDef(j)?Math.max(0,lpResourceBudget()-lpResourceSpent(j)):lpResourceBudget()),0);return `${chosen}/${lpCount()} paths · ${skillLeft+resLeft} dots left`}
 if(i===4){const total=c.attributeBudgets.reduce((a,b)=>a+b,0),used=totalAttributeSpent(),left=Math.max(0,total-used);return `${used}/${total} distributed · ${left} left`}
 if(i===5){const used=sum(state.freeSkills),left=Math.max(0,c.freeSkillDots-used);return `${used}/${c.freeSkillDots} free dots · ${left} left`}
 if(i===6){const req=D.skills.reduce((n,x)=>n+requiredFocuses(x.id),0),filled=D.skills.reduce((n,x)=>n+(state.focuses[x.id]||[]).filter(v=>String(v).trim()).length,0);return `${filled}/${req} Focuses · ${Math.max(0,req-filled)} left`}
 if(i===7){return `Dots ${totalClanDisciplineDots()}/${c.disciplineDots} · Powers ${state.disciplines.powers.length}/${c.disciplinePowers} · Traits ${state.traits.length}/${c.clanTraits} · Merits ${state.merits.length}/${c.merits}`}
 if(i===8)return `${state.humanity.nature?1:0}/1 Nature`;
 if(i===9){const used=freeResourceSpent();return `${used}/${c.freeResourceDots} free dots · ${Math.max(0,c.freeResourceDots-used)} left`}
 if(i===10){const req=1+lpCount(),done=(state.identity.name.trim()?1:0)+state.identity.items.filter(x=>String(x).trim()).length;return `${done}/${req} required fields · ${Math.max(0,req-done)} left`}
 return '';
}
function renderNav(){
 const nav=document.getElementById('navSteps'),mob=document.getElementById('mobileProgress');nav.innerHTML='';mob.innerHTML='';
 STEPS.forEach((s,i)=>{const issues=validateStep(i);const blocked=issues.some(x=>x.severity==='error');const done=isStepDone(i);const b=document.createElement('button');b.className=`navStep ${i===state.step?'active':''} ${done?'done':''} ${blocked?'blocked':''}`;b.innerHTML=`<span class="navStepLabel">${i+1}. ${e(s[0])}</span><span class="navProgress">${e(stepProgress(i))}</span>`;b.onclick=()=>goStep(i);nav.appendChild(b);const m=document.createElement('button');m.className=`mobileStep ${i===state.step?'active':''}`;m.textContent=`${i+1} ${s[0]}`;m.onclick=()=>goStep(i);mob.appendChild(m);});
}
function goStep(i){state.step=Math.max(0,Math.min(STEPS.length-1,i));state.info=infoForStep(state.step);closeDrawer();render();scrollTo({top:0,behavior:'instant'});}
function navFooter(){return `<div class="bottomNav"><button class="btn" data-action="prev" ${state.step===0?'disabled':''}>Back</button><button class="btn primary" data-action="next">${state.step===STEPS.length-1?'Review':'Next'}</button></div>`}
function issuesHtml(i){const a=validateStep(i);if(!a.length)return '<div class="notice good">This step is complete.</div>';return `<div class="issues">${a.map(x=>`<div class="issue ${x.severity}">${e(x.msg)}</div>`).join('')}</div>`}
function renderMain(){const f=[renderCreature,renderClan,renderSire,renderLifepaths,renderAttributes,renderSkills,renderFocuses,renderPowers,renderHumanity,renderResources,renderFinish][state.step];document.getElementById('mainCard').innerHTML=f()+navFooter();bindMain();}

function renderCreature(){const options=D.creatures.filter(c=>c.id.startsWith('vampire_'));return `<section class="step active"><h1>Step 1 · What Are You?</h1><div class="lead">Choose the vampire tier used for this character. It controls the RAW creation budgets and maximum ratings.</div><div class="grid3">${options.map(c=>`<button class="choiceCard ${state.creature===c.id?'selected':''}" data-creature="${c.id}"><h3>${e(c.name)}</h3><div class="meta">Max dots ${c.maxDots} · Chargen max Discipline ${c.maxDisciplineDots} · Generation Modifier ${c.generationModifier}</div><div class="tagrow"><span class="tag">${c.lifepaths} Lifepaths</span><span class="tag">Attributes ${c.attributeBudgets.join('/')}</span><span class="tag">${c.disciplineDots}+${c.sireBonus} Discipline dots</span></div></button>`).join('')}</div>${tierOf()==='neonate'?`<div class="sectionTitle">Optional young character rule</div><label class="card checkline"><input type="checkbox" id="youngToggle" ${state.young?'checked':''}><div><b>Use one Lifepath</b><div class="meta">${e(D.youngCharacter)} The project Lifepath Skill Cap house rule overrides the RAW cap-3 sentence: a Skill listed by this Lifepath has chargen cap 4.</div></div></label>`:''}${issuesHtml(0)}</section>`}
function renderClan(){const selected=clanById(state.clan.id);return `<section class="step active"><h1>Step 2 · Your Clan</h1><div class="lead">Choose a clan. Long descriptions use list rows on desktop so each entry keeps its natural height.</div>${selected?`<div class="selectedSummary"><div><div class="meta">Selected clan</div><b>${e(selected.name)}</b><div class="tagrow"><span class="tag">${e(selected.disciplineText)}</span>${selected.complete?'<span class="tag good">Full Alpha entry</span>':'<span class="tag warn">In development</span>'}</div></div><button class="infoBtn" data-info-clan="${selected.id}">Read clan</button></div>${renderClanDisciplineChoice()}`:''}<div class="sectionTitle">Clan list</div><div class="optionList">${D.clans.map(c=>`<button class="choiceRow ${state.clan.id===c.id?'selected':''} ${!c.complete?'incomplete':''}" data-clan="${c.id}"><div class="choiceRowMain"><div class="choiceRowTitle">${e(c.name)}</div><div class="choiceRowMeta">${e(c.description)}</div></div><div class="choiceRowAside"><span class="tag">${e(c.disciplineText)}</span>${c.complete?'<span class="tag good">Full Alpha</span>':'<span class="tag warn">In development</span>'}</div></button>`).join('')}</div>${issuesHtml(1)}</section>`}
function renderClanDisciplineChoice(){const c=clanById(state.clan.id);if(!c)return'';const r=c.disciplineRule||{};if(r.choice)return `<div class="requiredChoice"><div class="sectionTitle" style="margin-top:0">Required · choose ${e(c.name)}’s third Discipline</div><div class="grid2">${r.choice.map(id=>`<button class="choiceCompact ${state.clan.choice===id?'selected':''}" data-clan-choice="${id}"><b>${e(discById(id)?.name)}</b><span>${e(discById(id)?.description)}</span></button>`).join('')}</div></div>`;if(r.random)return `<div class="requiredChoice"><div class="sectionTitle" style="margin-top:0">Caitiff · 3 randomly determined Disciplines</div><div class="notice warn">RAW says these are randomly determined. Use Randomize for a RAW selection; manual changes remain available for table adjudication.</div><button class="btn" data-action="random-caitiff">Randomize 3</button><div class="optionList" style="margin-top:9px">${D.disciplines.map(d=>`<label class="choiceRow"><input type="checkbox" data-caitiff-disc="${d.id}" ${(state.clan.caitiffDisciplines||[]).includes(d.id)?'checked':''}><div class="choiceRowMain"><div class="choiceRowTitle">${e(d.name)}</div><div class="choiceRowMeta">${e(d.description)}</div></div></label>`).join('')}</div></div>`;return''}
function renderSire(){const s=byId(D.sires,state.sire.type),relatedNeeded=['adoptive_sire','brood_child'].includes(state.sire.type),allowed=sireAllowedDisciplines();return `<section class="step active"><h1>Step 3 · Sire & Generation</h1><div class="lead">Choose each part directly. This page no longer uses dropdowns for the primary chargen choices.</div><div class="sectionTitle">Sire type</div><div class="optionList">${D.sires.map(x=>`<button class="choiceRow ${state.sire.type===x.id?'selected':''}" data-sire-type="${x.id}"><div class="choiceRowMain"><div class="choiceRowTitle">${e(x.name)}</div><div class="choiceRowMeta">${e(x.description)}</div></div><div class="choiceRowAside"><span class="tag">Bonus: ${e(x.discipline)}</span></div></button>`).join('')}</div><div class="sectionTitle">Generation</div><div class="choiceChipGrid">${tierGenerations().map(g=>`<button class="choiceChip ${Number(state.generation)===g?'selected':''}" data-generation="${g}"><b>${g}th</b><span>Modifier ${D.generationModifiers[String(g)]}</span></button>`).join('')}</div>${relatedNeeded?`<div class="sectionTitle">${state.sire.type==='adoptive_sire'?'Adoptive sire':'Broodmate'} Clan</div><div class="choiceChipGrid">${D.clans.map(c=>`<button class="choiceChip ${state.sire.relatedClan===c.id?'selected':''}" data-related-clan="${c.id}"><b>${e(c.name)}</b></button>`).join('')}</div>`:''}<div class="sectionTitle">Bonus Discipline</div>${allowed.length?`<div class="grid3">${allowed.map(id=>`<button class="choiceCompact ${state.sire.bonusDiscipline===id?'selected':''}" data-sire-bonus="${id}"><b>${e(discById(id)?.name)}</b><span>${e(discById(id)?.description)}</span></button>`).join('')}</div>`:'<div class="notice warn">Choose the sire type'+(relatedNeeded?' and related Clan':'')+' first.</div>'}${s?`<div class="notice"><b>${e(s.name)}</b> · ${e(s.discipline)}</div>`:''}${issuesHtml(2)}</section>`}
function renderLifepaths(){ensureLpSlots();return `<section class="step active"><h1>Step 4 · Your Lifepaths</h1><div class="lead">Choose ${lpCount()} Lifepath${lpCount()===1?'':'s'}. Allocate ${lpSkillBudget()} Skill dots and ${lpResourceBudget()} Resource dots inside each.</div>${state.lifepaths.map((lp,i)=>renderLpSlot(lp,i)).join('')}${issuesHtml(3)}</section>`}
function renderLpSlot(lp,slot){const d=lpDef(slot),allowed=allowedLifepaths();return `<div class="lpCard"><div class="lpHead"><div><div class="sectionTitle" style="margin:0 0 6px">Lifepath ${slot+1}</div>${d?`<b style="font-size:18px">${e(d.name)}</b><div class="meta">${e(d.description)}</div>`:'<div class="meta">Choose a Lifepath.</div>'}</div><div class="field" style="margin:0"><label>Selection</label><select data-lp-select="${slot}"><option value="">Choose…</option>${allowed.map(x=>`<option value="${x.id}" ${lp.id===x.id?'selected':''}>${e(x.name)}${x.type==='vampire'?` · ${x.tier}`:''}</option>`).join('')}<option value="__custom__" ${lp.id==='__custom__'?'selected':''}>Custom Lifepath (RAW)</option></select></div></div>${lp.id==='__custom__'?renderCustomLp(lp,slot):''}${d?`<div class="budgetBar"><span class="pill ${sum(lp.skillDots)===lpSkillBudget()?'good':'warn'}">Skill dots ${sum(lp.skillDots)} / ${lpSkillBudget()}</span><span class="pill ${lpResourceSpent(slot)===lpResourceBudget()?'good':'warn'}">Resource dots ${lpResourceSpent(slot)} / ${lpResourceBudget()}</span><button class="infoBtn" data-info-lp="${slot}">Info</button></div><div class="sectionTitle">Lifepath Skills</div><div class="lpSkillGrid">${(d.skills||[]).map(x=>renderLpSkill(slot,x)).join('')}</div><div class="sectionTitle">Lifepath Resources</div><div class="lpResGrid">${(d.resources||[]).map((r,ri)=>renderLpResource(slot,r,ri)).join('')}</div>`:''}</div>`}
function renderCustomLp(lp,slot){const c=lp.custom||{name:'',description:'',skills:[],resources:[]};const skillSet=new Set(c.skills||[]);return `<div class="grid2"><div class="field"><label>Custom Lifepath name</label><input data-custom-name="${slot}" value="${e(c.name||'')}"></div><div class="field"><label>Description</label><input data-custom-desc="${slot}" value="${e(c.description||'')}"></div></div><div class="sectionTitle">Choose exactly 5 Skills</div><div class="gridAuto">${D.skills.map(s=>`<label class="card checkline"><input type="checkbox" data-custom-skill="${slot}:${s.id}" ${skillSet.has(s.id)?'checked':''}><div><b>${e(s.name)}</b><div class="meta">${e(s.description)}</div></div></label>`).join('')}</div><div class="sectionTitle">Define exactly 3 Resource types</div><div class="grid3">${[0,1,2].map(ri=>{const r=c.resources?.[ri]||{type:'',label:''};return `<div class="card"><div class="field"><label>Resource ${ri+1}</label><select data-custom-res-type="${slot}:${ri}"><option value="">Choose…</option>${D.resourceTypes.map(x=>`<option value="${x.id}" ${r.type===x.id?'selected':''}>${e(x.name)}</option>`).join('')}</select></div><div class="field"><label>Specific label</label><input data-custom-res-label="${slot}:${ri}" value="${e(r.label||'')}"></div></div>`}).join('')}</div>`}
function renderLpSkill(slot,x){const n=Number(state.lifepaths[slot].skillDots?.[x.skill]||0),s=skillById(x.skill),cap=skillCap(x.skill),sources=lifepathCapSources(x.skill);return `<div class="row"><div><div class="rowname">${e(s?.name||x.skill)} ${lifepathFocusLabel(x)?`<span class="tag">Suggested Focus: ${e(lifepathFocusLabel(x))}</span>`:''}</div><div class="rowmeta">Final rating ${finalSkill(x.skill)} / cap ${cap} · house-rule cap bonus +${sources.length}</div></div>${stepper(`lp-skill:${slot}:${x.skill}`,n,0,lpSkillBudget())}</div>`}
function renderLpResource(slot,r,ri){const n=Number(state.lifepaths[slot].resourceDots?.[String(ri)]||0),rt=resourceType(r.type);return `<div class="row"><div><div class="rowname">${e(rt?.name||r.type)}${r.label?`: ${e(r.label)}`:''}</div><div class="rowmeta">${e(rt?.category||'Resource')}</div></div>${stepper(`lp-res:${slot}:${ri}`,n,0,lpResourceBudget())}</div>`}
function stepper(key,n,min,max){return `<div class="stepper"><button data-stepper="${key}" data-delta="-1" ${n<=min?'disabled':''}>−</button><div class="n">${n}</div><button data-stepper="${key}" data-delta="1" ${n>=max?'disabled':''}>+</button></div>`}

function roleSwapValid(key,newRole){const roles={...state.attributes.roles},oldRole=roles[key];if(newRole===oldRole)return true;const other=Object.keys(roles).find(k=>k!==key&&roles[k]===newRole);if(!other)return false;roles[key]=newRole;roles[other]=oldRole;const budgetFor=(k)=>{const r=roles[k],b=creature().attributeBudgets;return r==='primary'?b[0]:r==='secondary'?b[1]:b[2]};return categorySpent(key[0].toUpperCase()+key.slice(1))<=budgetFor(key)&&categorySpent(other[0].toUpperCase()+other.slice(1))<=budgetFor(other)}
function maxLegalAttrRating(a){const current=Number(state.attributes.ratings[a.id]||1),spent=categorySpent(a.category),target=roleBudget(a.category);return Math.max(1,Math.min(attrMax(),current+Math.max(0,target-spent)))}
function attrRatingAllowed(a,rating){return rating>=1&&rating<=maxLegalAttrRating(a)}
function renderAttributes(){return `<section class="step active"><h1>Step 5 · Attributes</h1><div class="lead">Every Attribute starts at 1. Assign the primary, secondary, and tertiary budgets as additional dots above that baseline. Choices are blocked immediately when they would exceed the category allocation or the tier’s Max Dots.</div><div class="notice">RAW tier Max Dots: Neonate 5, Ancilla 6, Elder 8. Attribute budgets (7/5/3, 8/6/4, 9/7/5) are dots distributed above the free 1-dot baseline in every Attribute. Final category totals are therefore budget + 3. The Alpha provides qualitative rating descriptions only through 5.</div><div class="attrCols">${['Physical','Social','Mental'].map(renderAttrCat).join('')}</div><div class="derived" style="margin-top:10px"><div class="card"><div class="meta">Vitae Maximum</div><b>${vitaeMax()}</b><div class="meta">10 + Stamina</div></div><div class="card"><div class="meta">Willpower Maximum</div><b>${willpowerMax()}</b><div class="meta">5 + Composure + Resolve</div></div></div>${issuesHtml(4)}</section>`}
function renderAttrCat(cat){const key=cat.toLowerCase(),target=roleBudget(cat),spent=categorySpent(cat),left=Math.max(0,target-spent),finalTotal=categorySum(cat);return `<div class="attrCol"><div class="attrColHead"><div><b>${cat}</b><div class="meta">${spent} / ${target} distributed · ${left} left · final ${finalTotal}</div></div><select class="roleSelect" data-role="${key}" aria-label="${cat} category priority">${['primary','secondary','tertiary'].map(r=>`<option value="${r}" ${state.attributes.roles[key]===r?'selected':''} ${roleSwapValid(key,r)?'':'disabled'}>${r[0].toUpperCase()+r.slice(1)}</option>`).join('')}</select></div>${D.attributes.filter(a=>a.category===cat).map(a=>{const n=Number(state.attributes.ratings[a.id]);return `<div class="attrItem"><div class="attrItemTop"><button class="attrNameBtn" data-info-attr="${a.id}">${e(a.name)}</button><span class="attrCurrent">Rating ${n} · max now ${maxLegalAttrRating(a)}</span></div><div class="attrRatings">${Array.from({length:attrMax()},(_,i)=>{const r=i+1,allowed=attrRatingAllowed(a,r)||r===n;return `<button class="ratingBtn ${r===n?'selected':''}" data-attr="${a.id}" data-rating="${r}" ${allowed?'':'disabled'} aria-label="Set ${e(a.name)} to ${r}">${r}</button>`}).join('')}<button class="attrHelp" data-info-attr="${a.id}" aria-label="Read ${e(a.name)} description and rating scale">Info</button></div></div>`}).join('')}</div>`}
function renderSkills(){const fromLp=D.skills.filter(s=>lifepathSkillRating(s.id)>0),freeOnly=D.skills.filter(s=>lifepathSkillRating(s.id)===0);return `<section class="step active"><h1>Step 6 · Skills</h1><div class="lead">Ratings earned through Lifepaths stay in place. Spend ${creature().freeSkillDots} additional Skill dots without reducing any Lifepath rating.</div><div class="budgetBar"><span class="pill ${sum(state.freeSkills)===creature().freeSkillDots?'good':'warn'}">Free Skill dots ${sum(state.freeSkills)} / ${creature().freeSkillDots}</span><span class="pill">House rule: base cap 3 +1 per Lifepath listing the Skill</span></div><div class="sectionTitle">From Lifepaths</div>${fromLp.length?`<div class="optionList">${fromLp.map(renderSkillRow).join('')}</div>`:'<div class="notice">No Skill dots have been assigned through Lifepaths yet.</div>'}<div class="sectionTitle">Other Skills · free allocation</div><div class="optionList">${freeOnly.map(renderSkillRow).join('')}</div>${issuesHtml(5)}</section>`}
function renderSkillRow(s){const base=lifepathSkillRating(s.id),free=Number(state.freeSkills[s.id]||0),total=base+free,sources=lifepathSkillSources(s.id),capSources=lifepathCapSources(s.id),cap=skillCap(s.id);const canDown=free>0,canUp=sum(state.freeSkills)<creature().freeSkillDots&&total<cap;return `<div class="skillRow"><div class="skillRowMain"><button class="infoBtn" data-info-skill="${s.id}">${e(s.name)}</button><div class="rowmeta">Rating ${total} / cap ${cap}${capSources.length?` · cap +${capSources.length} (${capSources.map(e).join(' · ')})`:''}${base?` · Lifepath dots ${base}${sources.length?` (${sources.map(x=>`${e(x.source)} +${x.dots}`).join(' · ')})`:''}`:''}${free?` · Free +${free}`:''}</div><div class="choiceRowMeta">${e(s.description)}</div></div><div class="stepper"><button data-stepper="free-skill:${s.id}" data-delta="-1" ${canDown?'':'disabled'}>−</button><div class="n">${total}</div><button data-stepper="free-skill:${s.id}" data-delta="1" ${canUp?'':'disabled'}>+</button></div></div>`}
function renderFocuses(){ensureFocusSlots();const relevant=D.skills.filter(s=>requiredFocuses(s.id)>0),fromLp=relevant.filter(s=>lifepathCapSources(s.id).length>0),freeOnly=relevant.filter(s=>lifepathCapSources(s.id).length===0);return `<section class="step active"><h1>Step 7 · Focuses</h1><div class="lead">A Skill gains Focus slots at ratings 1, 3, and 5. Every Focus is selected by the player. Lifepath parentheticals are presented as recommendations, not fixed values.</div><div class="notice">Suggested Lifepath Focuses appear first when available. RAW Skill examples remain available as quick choices, and you can always type another relevant Focus.</div><div class="sectionTitle">Skills from selected Lifepaths</div>${fromLp.length?`<div class="optionList">${fromLp.map(renderFocusRow).join('')}</div>`:'<div class="notice">No current Focus-bearing Skill is listed by a selected Lifepath.</div>'}<div class="sectionTitle">Other Skills</div>${freeOnly.length?`<div class="optionList">${freeOnly.map(renderFocusRow).join('')}</div>`:'<div class="notice">No other Skill currently has a Focus slot.</div>'}${issuesHtml(6)}</section>`}
function renderFocusRow(s){const slots=focusSlotDefs(s.id),arr=state.focuses[s.id]||[],capSources=lifepathCapSources(s.id),recs=lifepathFocusRecommendations(s.id);return `<div class="focusCard"><div class="focusHead"><div><button class="infoBtn" data-info-skill="${s.id}">${e(s.name)}</button><div class="rowmeta">Rating ${finalSkill(s.id)} · cap ${skillCap(s.id)}${capSources.length?` · Lifepaths: ${capSources.map(e).join(' · ')}`:''} · ${slots.length} Focus slot${slots.length===1?'':'s'}</div></div></div>${recs.length?`<div class="focusRecommendationSummary">${recs.map(r=>`<span><b>${e(r.source)}</b>${r.values.length?`: ${r.values.map(e).join(' / ')}`:r.prompt?`: ${e(r.prompt)}`:''}</span>`).join('')}</div>`:''}<div class="focusInputs">${slots.map((slot,i)=>renderFocusSlot(s,slot,i,arr[i]||'')).join('')}</div></div>`}
function renderFocusSlot(s,slot,i,value){const recs=lifepathFocusRecommendations(s.id),lpValues=[],prompts=[];recs.forEach(r=>{r.values.forEach(v=>{if(!lpValues.includes(v))lpValues.push(v)});if(r.prompt)prompts.push(`${r.source}: ${r.prompt}`)});const raw=rawFocusSuggestions(s.id).filter(v=>!lpValues.includes(v)),all=[...lpValues,...raw];return `<div class="focusSlot"><div class="focusSlotHead"><b>Focus at rating ${slot.threshold}</b><span class="tag">Player choice</span></div><div class="field" style="margin:0"><input list="focus-${s.id}-${i}" data-focus="${s.id}:${i}" value="${e(value)}" placeholder="Choose or type a Focus"><datalist id="focus-${s.id}-${i}">${all.map(x=>`<option value="${e(x)}"></option>`).join('')}</datalist></div>${lpValues.length?`<div class="focusChoiceLabel">Suggested by Lifepath</div><div class="focusSuggestions">${lpValues.map(x=>`<button type="button" class="focusSuggestion recommended" data-focus-pick="${s.id}:${i}" data-focus-value="${e(x)}">${e(x)}</button>`).join('')}</div>`:''}${prompts.length?`<div class="rowmeta focusPromptNote">${prompts.map(e).join(' · ')}</div>`:''}${raw.length?`<div class="focusChoiceLabel">RAW Skill examples</div><div class="focusSuggestions">${raw.slice(0,10).map(x=>`<button type="button" class="focusSuggestion" data-focus-pick="${s.id}:${i}" data-focus-value="${e(x)}">${e(x)}</button>`).join('')}</div>`:''}<div class="rowmeta">Suggestions are optional. Enter another relevant Focus if it better fits the character.</div></div>`}

function renderPowers(){const c=creature(),cl=clanById(state.clan.id),cds=clanDisciplineIds(),needsChoice=!!(cl?.disciplineRule?.choice&&!state.clan.choice),sireOnly=state.sire.bonusDiscipline&&!cds.includes(state.sire.bonusDiscipline)?state.sire.bonusDiscipline:null,caps=tierDisciplineCaps();return `<section class="step active"><h1>Step 8 · Disciplines, Clan Traits & Merits</h1><div class="lead">Spend ${c.disciplineDots} dots only among the three Clan Disciplines. The sire-granted dot is already present and cannot be removed. Then choose ${c.disciplinePowers} powers, ${c.clanTraits} Clan Traits, and ${c.merits} Merits.</div>${needsChoice?`<div class="notice warn"><b>${e(cl.name)}’s variable Clan Discipline has not been resolved.</b> Make that choice once on the Clan page before allocating Discipline dots. <button class="btn ghost" type="button" data-action="go-clan" style="margin-left:8px;min-height:32px">Open Clan step</button></div>`:''}<div class="sectionTitle">Discipline dots</div><div class="budgetBar"><span class="pill ${totalClanDisciplineDots()===c.disciplineDots?'good':'warn'}">Clan dots ${totalClanDisciplineDots()} / ${c.disciplineDots}</span><span class="pill">Sire bonus: ${state.sire.bonusDiscipline?e(discById(state.sire.bonusDiscipline)?.name)+' 1':'not selected'}</span><span class="pill">Chargen max ${c.maxDisciplineDots}</span></div><div class="notice">RAW says to distribute the listed dots among the three Clan Disciplines; it does not state a mandatory 3/2/1-style spread. Tier caps after character creation are Clan ${caps.clan} / Non-Clan ${caps.nonClan}.</div><div class="grid3">${cds.map(id=>renderDiscDotCard(id)).join('')||'<div class="notice warn">Complete the Clan Discipline choice first.</div>'}${sireOnly?renderSireOnlyDiscCard(sireOnly):''}</div><div class="sectionTitle">Discipline powers</div><div class="budgetBar"><span class="pill ${state.disciplines.powers.length===c.disciplinePowers?'good':'warn'}">Powers ${state.disciplines.powers.length} / ${c.disciplinePowers}</span></div>${renderPowerGroups()}<div class="sectionTitle">Clan Traits</div><div class="budgetBar"><span class="pill ${state.traits.length===c.clanTraits?'good':'warn'}">Traits ${state.traits.length} / ${c.clanTraits}</span></div>${cl?.complete?`<div class="gridAuto">${cl.traits.map(renderTraitCard).join('')}</div>`:`<div class="notice warn">The supplied Alpha packet does not provide a full Clan Trait set for ${e(cl?.name||'this clan')}.</div>`}<div class="sectionTitle">Merits</div><div class="budgetBar"><span class="pill ${state.merits.length===c.merits?'good':'warn'}">Merits ${state.merits.length} / ${c.merits}</span></div><div class="gridAuto">${D.merits.map(renderMeritCard).join('')}</div>${issuesHtml(7)}</section>`}
function renderDiscDotCard(id){const d=discById(id),free=Number(state.disciplines.clanDots[id]||0),rating=disciplineRating(id),sire=state.sire.bonusDiscipline===id,canDown=free>0,canUp=totalClanDisciplineDots()<creature().disciplineDots&&rating<creature().maxDisciplineDots;return `<div class="card"><div class="row"><div><div class="rowname">${e(d.name)}</div><div class="rowmeta">Rating ${rating} · Clan allocation ${free}${sire?' · Sire +1':''}${sourceGapDisc(id)?' · powers in development':''}</div></div><div class="stepper"><button data-stepper="disc:${id}" data-delta="-1" ${canDown?'':'disabled'}>−</button><div class="n">${rating}</div><button data-stepper="disc:${id}" data-delta="1" ${canUp?'':'disabled'}>+</button></div></div><button class="infoBtn" data-info-disc="${id}">Discipline info</button></div>`}
function renderSireOnlyDiscCard(id){const d=discById(id);return `<div class="card"><div class="row"><div><div class="rowname">${e(d.name)}</div><div class="rowmeta">Rating 1 · granted by Sire · non-Clan at chargen</div></div><div class="stepper"><button disabled>−</button><div class="n">1</div><button disabled>+</button></div></div><button class="infoBtn" data-info-disc="${id}">Discipline info</button></div>`}
function renderPowerGroups(){const ids=D.disciplines.filter(d=>disciplineRating(d.id)>0).map(d=>d.id);if(!ids.length)return '<div class="notice warn">No eligible powers yet. Add or receive a Discipline dot first.</div>';return ids.map(id=>{const d=discById(id),r=disciplineRating(id),powers=(d.powers||[]).filter(p=>p.rank<=r),sel=state.disciplines.powers.filter(x=>x.disciplineId===id).length;return `<div class="powerGroup"><div class="powerGroupHead"><div><b>${e(d.name)}</b><div class="meta">Rating ${r} · ${sel} power${sel===1?'':'s'} selected</div></div><button class="infoBtn" data-info-disc="${id}">Discipline info</button></div>${powers.length?`<div class="gridAuto">${powers.map(p=>renderPowerCard({...p,disciplineId:id,disciplineName:d.name})).join('')}</div>`:`<div class="notice warn">No full power definitions for this Discipline are supplied in the Alpha packet.</div>`}</div>`}).join('')}
function renderPowerCard(p){const sel=powerSelected(p.disciplineId,p.id);return `<div class="powerCard selectable ${sel?'selected':''}" data-power="${p.disciplineId}:${p.id}"><div class="checkline"><input type="checkbox" ${sel?'checked':''} tabindex="-1"><div><b>${e(p.name)}</b><div class="meta">${e(p.disciplineName)} · ${p.rank}-dot ${e(p.category)}</div></div></div><div class="powerMeta"><span class="tag">${e(p.cost||'Cost —')}</span><span class="tag">${e(p.activate||'Action —')}</span>${p.detailsMissing?'<span class="tag warn">full entry missing</span>':''}<button class="infoBtn" data-info-power="${p.disciplineId}:${p.id}">Read full power</button></div></div>`}
function renderTraitCard(t){const ok=traitEligible(t),sel=state.traits.includes(t.id);return `<div class="traitCard selectable ${sel?'selected':''} ${!ok?'disabled':''}" data-trait="${t.id}"><div class="checkline"><input type="checkbox" ${sel?'checked':''} ${!ok?'disabled':''} tabindex="-1"><div><b>${e(t.name)}</b><div class="meta">${e(t.prerequisites)}</div></div></div><button class="infoBtn" data-info-trait="${t.id}" style="margin-top:8px">Read trait</button></div>`}
function renderMeritCard(m){const ok=prereqEligible(m.prerequisites),sel=state.merits.includes(m.id);return `<div class="meritCard selectable ${sel?'selected':''} ${!ok?'disabled':''}" data-merit="${m.id}"><div class="checkline"><input type="checkbox" ${sel?'checked':''} ${!ok?'disabled':''} tabindex="-1"><div><b>${e(m.name)}</b><div class="meta">${e(m.summary)}</div></div></div><button class="infoBtn" data-info-merit="${m.id}" style="margin-top:8px">Read Merit</button></div>`}

function humanityPositions(){const t=tierOf();if(t==='ancilla')return[{v:-1,l:'Monstrous 1'},{v:0,l:'Neutral'},{v:1,l:'Mortal 1'}];if(t==='elder')return[{v:-2,l:'Monstrous 2'},{v:0,l:'Neutral'},{v:2,l:'Mortal 2'}];return[{v:0,l:'Neutral'}]}
function renderHumanity(){return `<section class="step active"><h1>Step 9 · Humanity Scale & Nature</h1><div class="lead">Choose the permitted starting Humanity position and the Nature that represents the character’s mortal axis.</div><div class="sectionTitle">Starting Humanity</div><div class="grid3">${humanityPositions().map(x=>`<button class="choiceCard ${state.humanity.position===x.v?'selected':''}" data-humanity="${x.v}"><h3>${e(x.l)}</h3><div class="meta">${x.v===0?'Middle dot of the 7-dot Humanity Scale.':'Optional unbalanced beginning if the Storyteller uses that rule.'}</div></button>`).join('')}</div><div class="sectionTitle">Nature</div><div class="gridAuto">${D.natures.map(n=>`<div class="natureCard selectable ${state.humanity.nature===n.id?'selected':''}" data-nature="${n.id}"><b>${e(n.name)}</b><div class="meta">${e(n.summary)}</div><button class="infoBtn" data-info-nature="${n.id}" style="margin-top:8px">Read Nature & Outburst</button></div>`).join('')}</div>${issuesHtml(8)}</section>`}

function renderResources(){const c=creature(),agg=aggregatedLifepathResources();return `<section class="step active"><h1>Step 10 · Your Resources</h1><div class="lead">Matching Resources from multiple Lifepaths are combined into one rating. Each entry shows the contributing Lifepaths and the Resource description.</div><div class="sectionTitle">From Lifepaths</div><div class="grid2">${agg.map(r=>{const rt=resourceType(r.type);return `<div class="card"><b>${e(rt?.name||r.type)} ${dots(r.dots)}</b>${r.label?`<div class="meta">${e(r.label)}</div>`:''}<div class="choiceRowMeta" style="margin-top:7px">${e(rt?.description||'')}</div><div class="tagrow">${r.sources.map(x=>`<span class="tag">${e(x.source)} +${x.dots}</span>`).join('')}</div><button class="infoBtn" data-info-resource="${r.type}" style="margin-top:8px">Resource info</button></div>`}).join('')||'<div class="notice warn">No Lifepath Resource dots allocated yet.</div>'}</div><div class="sectionTitle">Free Resources</div><div class="budgetBar"><span class="pill ${freeResourceSpent()===c.freeResourceDots?'good':'warn'}">Free dots ${freeResourceSpent()} / ${c.freeResourceDots}</span><button class="btn" data-action="add-resource" ${freeResourceSpent()>=c.freeResourceDots?'disabled':''}>Add Resource</button></div>${state.resources.free.map((r,i)=>renderFreeResource(r,i)).join('')}${issuesHtml(9)}</section>`}
function renderFreeResource(r,i){return `<div class="resourceEntry"><div class="field"><label>Type</label><select data-free-res-type="${i}"><option value="">Choose…</option>${D.resourceTypes.map(x=>`<option value="${x.id}" ${r.type===x.id?'selected':''}>${e(x.name)}</option>`).join('')}</select></div><div class="field"><label>Specific label</label><input data-free-res-label="${i}" value="${e(r.label||'')}" placeholder="e.g. Armory, Dresden court, BMW 5 Series"></div><div class="field"><label>Dots</label><input data-free-res-dots="${i}" type="number" min="1" max="${attrMax()}" value="${Number(r.dots||1)}"></div><button class="btn danger" data-remove-resource="${i}">Remove</button></div>`}

function renderFinish(){const issues=allIssues();return `<section class="step active"><h1>Step 11 · Finishing Touches</h1><div class="lead">Complete identity details, important items, and optional Flaws. The review below is generated directly from current state.</div><div class="grid2"><div class="field"><label>Name</label><input id="charName" value="${e(state.identity.name)}"></div><div class="field"><label>Alias</label><input id="charAlias" value="${e(state.identity.alias)}"></div><div class="field"><label>Apparent Age</label><input id="apparentAge" value="${e(state.identity.apparentAge)}"></div><div class="field"><label>Actual Age</label><input id="actualAge" value="${e(state.identity.actualAge)}"></div><div class="field"><label>Nostalgic Decade</label><input id="nostalgicDecade" value="${e(state.identity.nostalgicDecade)}"></div></div><div class="sectionTitle">Important items · one per Lifepath</div><div class="grid2">${state.identity.items.map((x,i)=>`<div class="field"><label>${e(lpDef(i)?.name||`Lifepath ${i+1}`)} item</label><input data-important-item="${i}" value="${e(x)}"></div>`).join('')}</div><div class="field"><label>Flaws (optional, free text)</label><textarea id="flaws">${e(state.identity.flaws)}</textarea></div><div class="sectionTitle">Derived</div><div class="derived"><div class="card"><div class="meta">Vitae Maximum</div><b>${vitaeMax()}</b></div><div class="card"><div class="meta">Willpower Maximum</div><b>${willpowerMax()}</b></div></div><div class="sectionTitle">Character Review</div>${reviewHtml()}<div class="sectionTitle">Validation</div>${issues.length?`<div class="issues">${issues.map(x=>`<div class="issue ${x.severity}">Step ${x.step+1}: ${e(x.msg)}</div>`).join('')}</div>`:'<div class="notice good">Character is complete under the implemented Alpha rules.</div>'}${issuesHtml(10)}</section>`}
function reviewSkillItem(s){const r=finalSkill(s.id),fs=(state.focuses[s.id]||[]).filter(x=>String(x).trim());return `<div class="reviewSkillItem"><div class="reviewItemHead"><b>${e(s.name)}</b><span class="reviewRating">${r}</span></div>${fs.length?`<div class="reviewTags">${fs.map(f=>`<span class="reviewTag">${e(f)}</span>`).join('')}</div>`:'<div class="reviewEmpty">No Focus selected</div>'}</div>`}
function reviewDisciplineGroup(d){const r=disciplineRating(d.id),powers=state.disciplines.powers.map(x=>x.disciplineId===d.id?d.powers.find(p=>p.id===x.powerId):null).filter(Boolean).sort((a,b)=>a.rank-b.rank||a.name.localeCompare(b.name));return `<div class="reviewDiscGroup"><div class="reviewDiscHead"><b>${e(d.name)}</b><span class="reviewRating">${r}</span></div>${powers.length?`<div class="reviewPowerList">${powers.map(p=>`<div class="reviewPowerRow"><span>${e(p.name)}</span><span class="reviewPowerRank">Rank ${p.rank}</span></div>`).join('')}</div>`:'<div class="reviewEmpty">No selected powers</div>'}</div>`}
function reviewNameTags(items){return items.length?`<div class="reviewTags">${items.map(x=>`<span class="reviewTag">${e(x)}</span>`).join('')}</div>`:'<div class="reviewEmpty">—</div>'}
function reviewHtml(){const c=clanById(state.clan.id),s=byId(D.sires,state.sire.type),n=byId(D.natures,state.humanity.nature),skills=D.skills.filter(x=>finalSkill(x.id)>0),discs=D.disciplines.filter(d=>disciplineRating(d.id)>0),traits=state.traits.map(id=>c?.traits.find(t=>t.id===id)?.name).filter(Boolean),merits=state.merits.map(id=>byId(D.merits,id)?.name).filter(Boolean);return `<div class="reviewGrid"><div class="card"><div class="sectionTitle" style="margin-top:0">Identity</div>${kv('Clan',c?.name||'—')}${kv('Tier',creature().name)}${kv('Generation',`${state.generation} · modifier ${generationModifier()}`)}${kv('Sire',s?.name||'—')}${kv('Nature',n?.name||'—')}${kv('Humanity',humanityPositions().find(x=>x.v===state.humanity.position)?.l||'—')}</div><div class="card"><div class="sectionTitle" style="margin-top:0">Attributes</div>${D.attributes.map(a=>kv(a.name,dots(state.attributes.ratings[a.id]))).join('')}</div><div class="card reviewWide"><div class="sectionTitle" style="margin-top:0">Skills</div><div class="reviewSkillGrid">${skills.map(reviewSkillItem).join('')||'<div class="reviewEmpty">—</div>'}</div></div><div class="card reviewWide"><div class="sectionTitle" style="margin-top:0">Disciplines & Powers</div><div class="reviewDiscGrid">${discs.map(reviewDisciplineGroup).join('')||'<div class="reviewEmpty">—</div>'}</div><div class="reviewSubsection"><b>Clan Traits</b>${reviewNameTags(traits)}</div><div class="reviewSubsection"><b>Merits</b>${reviewNameTags(merits)}</div></div><div class="card"><div class="sectionTitle" style="margin-top:0">Lifepaths</div><div class="meta">${state.lifepaths.map((_,i)=>e(lpDef(i)?.name||'—')).join(' · ')}</div></div><div class="card"><div class="sectionTitle" style="margin-top:0">Resources</div><div class="meta">${e([...aggregatedLifepathResources(),...state.resources.free].filter(r=>r.type).map(r=>`${resourceType(r.type)?.name||r.type}${r.label?`: ${r.label}`:''} ${r.dots}`).join(' · ')||'—')}</div></div></div>`}
function kv(k,v){return `<div class="kv"><span>${e(k)}</span><b>${e(v)}</b></div>`}

function bindMain(){const root=document.getElementById('mainCard');
 root.querySelectorAll('[data-action="prev"]').forEach(b=>b.onclick=()=>goStep(state.step-1));root.querySelectorAll('[data-action="next"]').forEach(b=>b.onclick=()=>goStep(Math.min(state.step+1,STEPS.length-1)));root.querySelectorAll('[data-action="go-clan"]').forEach(b=>b.onclick=()=>goStep(1));
 root.querySelectorAll('[data-info-step]').forEach(b=>b.onclick=ev=>{ev.stopPropagation();setInfo(infoForStep(Number(b.dataset.infoStep)),true)});
 root.querySelectorAll('[data-creature]').forEach(b=>b.onclick=()=>{const id=b.dataset.creature;if(id!==state.creature){const oldIdentity=state.identity;state=blankState();state.creature=id;state.identity={...state.identity,name:oldIdentity.name,alias:oldIdentity.alias};ensureGeneration();ensureLpSlots();ensureItems();}render()});
 const young=root.querySelector('#youngToggle');if(young)young.onchange=()=>{state.young=young.checked;state.lifepaths=[];state.freeSkills={};state.focuses={};state.resources.free=[];ensureLpSlots();ensureFocusSlots();ensureItems();render()};
 root.querySelectorAll('[data-clan]').forEach(b=>b.onclick=()=>{state.clan={id:b.dataset.clan,choice:null,caitiffDisciplines:[]};state.disciplines={clanDots:{},powers:[]};state.traits=[];state.sire.bonusDiscipline=null;setInfo(infoClan(b.dataset.clan),false);render()});
 root.querySelectorAll('[data-info-clan]').forEach(b=>b.onclick=ev=>{ev.stopPropagation();setInfo(infoClan(b.dataset.infoClan),true)});
 root.querySelectorAll('[data-clan-choice]').forEach(b=>b.onclick=()=>{state.clan.choice=b.dataset.clanChoice;state.disciplines={clanDots:{},powers:[]};state.traits=[];render()});
 root.querySelectorAll('[data-caitiff-disc]').forEach(x=>x.onchange=()=>{let a=state.clan.caitiffDisciplines||[];if(x.checked){if(a.length>=3){x.checked=false;return}a=[...a,x.dataset.caitiffDisc]}else a=a.filter(id=>id!==x.dataset.caitiffDisc);state.clan.caitiffDisciplines=a;state.disciplines={clanDots:{},powers:[]};render()});
 const rc=root.querySelector('[data-action="random-caitiff"]');if(rc)rc.onclick=()=>{const ids=D.disciplines.map(d=>d.id);for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}state.clan.caitiffDisciplines=ids.slice(0,3);state.disciplines={clanDots:{},powers:[]};render()};
 root.querySelectorAll('[data-sire-type]').forEach(b=>b.onclick=()=>{state.sire.type=b.dataset.sireType;state.sire.relatedClan=null;state.sire.bonusDiscipline=null;render()});
 root.querySelectorAll('[data-generation]').forEach(b=>b.onclick=()=>{state.generation=Number(b.dataset.generation);render()});
 root.querySelectorAll('[data-related-clan]').forEach(b=>b.onclick=()=>{state.sire.relatedClan=b.dataset.relatedClan;state.sire.bonusDiscipline=null;render()});
 root.querySelectorAll('[data-sire-bonus]').forEach(b=>b.onclick=()=>{state.sire.bonusDiscipline=b.dataset.sireBonus;state.disciplines.powers=state.disciplines.powers.filter(x=>disciplinesPowerStillValid(x));render()});
 root.querySelectorAll('[data-lp-select]').forEach(sel=>sel.onchange=()=>{const i=Number(sel.dataset.lpSelect);state.lifepaths[i]={id:sel.value||null,skillDots:{},resourceDots:{},custom:sel.value==='__custom__'?{name:'',description:'',skills:[],resources:[{type:'',label:''},{type:'',label:''},{type:'',label:''}]}:null};enforceSkillCaps();render()});
 root.querySelectorAll('[data-custom-name]').forEach(x=>x.oninput=()=>{state.lifepaths[Number(x.dataset.customName)].custom.name=x.value;save()});root.querySelectorAll('[data-custom-desc]').forEach(x=>x.oninput=()=>{state.lifepaths[Number(x.dataset.customDesc)].custom.description=x.value;save()});
 root.querySelectorAll('[data-custom-skill]').forEach(x=>x.onchange=()=>{const [si,id]=x.dataset.customSkill.split(':');const c=state.lifepaths[Number(si)].custom;let a=c.skills||[];if(x.checked){if(a.length>=5){x.checked=false;return}a=[...a,id]}else a=a.filter(y=>y!==id);c.skills=a;state.lifepaths[Number(si)].skillDots={};enforceSkillCaps();render()});
 root.querySelectorAll('[data-custom-res-type]').forEach(x=>x.onchange=()=>{const [si,ri]=x.dataset.customResType.split(':');state.lifepaths[Number(si)].custom.resources[Number(ri)].type=x.value;state.lifepaths[Number(si)].resourceDots={};render()});root.querySelectorAll('[data-custom-res-label]').forEach(x=>x.oninput=()=>{const [si,ri]=x.dataset.customResLabel.split(':');state.lifepaths[Number(si)].custom.resources[Number(ri)].label=x.value;save()});
 root.querySelectorAll('[data-stepper]').forEach(b=>b.onclick=()=>handleStepper(b.dataset.stepper,Number(b.dataset.delta)));
 root.querySelectorAll('[data-info-lp]').forEach(b=>b.onclick=()=>setInfo(infoLp(Number(b.dataset.infoLp)),true));
 root.querySelectorAll('[data-role]').forEach(sel=>sel.onchange=()=>{const key=sel.dataset.role,newRole=sel.value;if(!roleSwapValid(key,newRole)){render();return}const other=Object.keys(state.attributes.roles).find(k=>k!==key&&state.attributes.roles[k]===newRole);if(other){const old=state.attributes.roles[key];state.attributes.roles[other]=old}state.attributes.roles[key]=newRole;render()});
 root.querySelectorAll('[data-attr]').forEach(b=>b.onclick=()=>{const a=attrById(b.dataset.attr),r=Number(b.dataset.rating);if(!a||!attrRatingAllowed(a,r))return;state.attributes.ratings[a.id]=r;setInfo(infoAttribute(a.id),false);render()});root.querySelectorAll('[data-info-attr]').forEach(b=>b.onclick=()=>setInfo(infoAttribute(b.dataset.infoAttr),true));root.querySelectorAll('[data-info-skill]').forEach(b=>b.onclick=()=>setInfo(infoSkill(b.dataset.infoSkill),true));
 root.querySelectorAll('[data-focus]').forEach(x=>x.oninput=()=>{const [sid,i]=x.dataset.focus.split(':');state.focuses[sid][Number(i)]=x.value;save()});root.querySelectorAll('[data-focus-pick]').forEach(b=>b.onclick=()=>{const [sid,i]=b.dataset.focusPick.split(':');state.focuses[sid][Number(i)]=b.dataset.focusValue;render()});
 root.querySelectorAll('[data-info-disc]').forEach(b=>b.onclick=()=>{const d=discById(b.dataset.infoDisc);setInfo({kicker:'Discipline',title:d.name,summary:d.description,meta:[['Current rating',String(disciplineRating(d.id))],['Alpha powers',String(d.powers.length)]],body:d.powers.length?'Powers are listed by rank in the main panel. Select “Read full power” for activation, cost, Difficulty, distance, duration, and full rules text.':'The supplied Alpha packet lists this Discipline in clan summaries but does not provide Chapter 5 power definitions for it.',source:'Player Packet · Chapter 5: Powers of the Blood'},true)});
 root.querySelectorAll('[data-power]').forEach(card=>card.onclick=ev=>{if(ev.target.closest('[data-info-power]'))return;const [did,pid]=card.dataset.power.split(':');togglePower(did,pid)});root.querySelectorAll('[data-info-power]').forEach(b=>b.onclick=ev=>{ev.stopPropagation();const [did,pid]=b.dataset.infoPower.split(':');setInfo(infoPower(did,pid),true)});
 root.querySelectorAll('[data-trait]').forEach(card=>card.onclick=ev=>{if(ev.target.closest('[data-info-trait]'))return;const c=clanById(state.clan.id),t=c?.traits.find(t=>t.id===card.dataset.trait);if(!t||!traitEligible(t))return;toggleLimited(state.traits,t.id,creature().clanTraits);render()});root.querySelectorAll('[data-info-trait]').forEach(b=>b.onclick=ev=>{ev.stopPropagation();const t=clanById(state.clan.id)?.traits.find(t=>t.id===b.dataset.infoTrait);if(t)setInfo(infoTrait(t),true)});
 root.querySelectorAll('[data-merit]').forEach(card=>card.onclick=ev=>{if(ev.target.closest('[data-info-merit]'))return;const m=byId(D.merits,card.dataset.merit);if(!m||!prereqEligible(m.prerequisites))return;toggleLimited(state.merits,m.id,creature().merits);render()});root.querySelectorAll('[data-info-merit]').forEach(b=>b.onclick=ev=>{ev.stopPropagation();const m=byId(D.merits,b.dataset.infoMerit);if(m)setInfo(infoMerit(m),true)});
 root.querySelectorAll('[data-humanity]').forEach(b=>b.onclick=()=>{state.humanity.position=Number(b.dataset.humanity);render()});root.querySelectorAll('[data-nature]').forEach(card=>card.onclick=ev=>{if(ev.target.closest('[data-info-nature]'))return;state.humanity.nature=card.dataset.nature;render()});root.querySelectorAll('[data-info-nature]').forEach(b=>b.onclick=ev=>{ev.stopPropagation();const n=byId(D.natures,b.dataset.infoNature);setInfo(infoNature(n),true)});
 const ar=root.querySelector('[data-action="add-resource"]');if(ar)ar.onclick=()=>{state.resources.free.push({type:'',label:'',dots:1});render()};root.querySelectorAll('[data-free-res-type]').forEach(x=>x.onchange=()=>{state.resources.free[Number(x.dataset.freeResType)].type=x.value;render()});root.querySelectorAll('[data-free-res-label]').forEach(x=>x.oninput=()=>{state.resources.free[Number(x.dataset.freeResLabel)].label=x.value;save()});root.querySelectorAll('[data-free-res-dots]').forEach(x=>x.onchange=()=>{state.resources.free[Number(x.dataset.freeResDots)].dots=Math.max(1,Math.min(attrMax(),Number(x.value)||1));render()});root.querySelectorAll('[data-remove-resource]').forEach(b=>b.onclick=()=>{state.resources.free.splice(Number(b.dataset.removeResource),1);render()});root.querySelectorAll('[data-info-resource]').forEach(b=>b.onclick=()=>setInfo(infoResource(b.dataset.infoResource),true));
 bindText('charName',v=>state.identity.name=v);bindText('charAlias',v=>state.identity.alias=v);bindText('apparentAge',v=>state.identity.apparentAge=v);bindText('actualAge',v=>state.identity.actualAge=v);bindText('nostalgicDecade',v=>state.identity.nostalgicDecade=v);bindText('flaws',v=>state.identity.flaws=v);root.querySelectorAll('[data-important-item]').forEach(x=>x.oninput=()=>{state.identity.items[Number(x.dataset.importantItem)]=x.value;save()});
}
function bindText(id,set){const x=document.getElementById(id);if(x)x.oninput=()=>{set(x.value);save()}}
function handleStepper(key,delta){const parts=key.split(':');if(parts[0]==='lp-skill'){const slot=Number(parts[1]),sid=parts[2],lp=state.lifepaths[slot],cur=Number(lp.skillDots[sid]||0);if(delta>0&&(sum(lp.skillDots)>=lpSkillBudget()||finalSkill(sid)>=skillCap(sid)))return;lp.skillDots[sid]=Math.max(0,cur+delta);if(lp.skillDots[sid]===0)delete lp.skillDots[sid];ensureFocusSlots();setInfo(infoSkill(sid),false);render();return}
 if(parts[0]==='lp-res'){const slot=Number(parts[1]),ri=parts[2],lp=state.lifepaths[slot],cur=Number(lp.resourceDots[ri]||0);if(delta>0&&lpResourceSpent(slot)>=lpResourceBudget())return;lp.resourceDots[ri]=Math.max(0,cur+delta);if(lp.resourceDots[ri]===0)delete lp.resourceDots[ri];render();return}
 if(parts[0]==='free-skill'){const sid=parts[1],cur=Number(state.freeSkills[sid]||0);if(delta>0&&(sum(state.freeSkills)>=creature().freeSkillDots||finalSkill(sid)>=skillCap(sid)))return;state.freeSkills[sid]=Math.max(0,cur+delta);if(state.freeSkills[sid]===0)delete state.freeSkills[sid];ensureFocusSlots();setInfo(infoSkill(sid),false);render();return}
 if(parts[0]==='disc'){const id=parts[1],cur=Number(state.disciplines.clanDots[id]||0);if(delta>0&&(totalClanDisciplineDots()>=creature().disciplineDots||disciplineRating(id)>=creature().maxDisciplineDots))return;state.disciplines.clanDots[id]=Math.max(0,cur+delta);if(state.disciplines.clanDots[id]===0)delete state.disciplines.clanDots[id];state.disciplines.powers=state.disciplines.powers.filter(disciplinesPowerStillValid);state.traits=state.traits.filter(tid=>{const t=clanById(state.clan.id)?.traits.find(t=>t.id===tid);return t&&traitEligible(t)});state.merits=state.merits.filter(mid=>{const m=byId(D.merits,mid);return m&&prereqEligible(m.prerequisites)});render();return}}
function disciplinesPowerStillValid(x){const p=discById(x.disciplineId)?.powers.find(p=>p.id===x.powerId);return !!p&&p.rank<=disciplineRating(x.disciplineId)}
function togglePower(did,pid){const idx=state.disciplines.powers.findIndex(x=>x.disciplineId===did&&x.powerId===pid);if(idx>=0)state.disciplines.powers.splice(idx,1);else if(state.disciplines.powers.length<creature().disciplinePowers)state.disciplines.powers.push({disciplineId:did,powerId:pid});render()}
function toggleLimited(arr,id,max){const i=arr.indexOf(id);if(i>=0)arr.splice(i,1);else if(arr.length<max)arr.push(id)}

function exportJson(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vtm-v6-alpha-${(state.identity.name||'character').replace(/[^a-z0-9_-]+/gi,'_')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importJson(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.schemaVersion!==1)throw new Error('Unsupported schema');state=x;normalizeState();render()}catch(err){alert('Could not import this character JSON: '+err.message)}};r.readAsText(file)}

function bindGlobal(){document.getElementById('exportBtn').onclick=exportJson;document.getElementById('importFile').onchange=e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value=''};document.getElementById('resetBtn').onclick=()=>{if(confirm('Reset the current character?')){state=blankState();render()}};document.getElementById('drawerClose').onclick=closeDrawer;document.getElementById('drawerBack').onclick=closeDrawer;document.getElementById('mobileInfoTop').onclick=()=>{renderInfo();openDrawer()};}
bindGlobal();render();
})();
